### ISSUE TITLE
S.channels[channelId].notifyConfirm写法有误

### ISSUE THREAD

**Issue by kurolz** [Braveheart7854/rabbitmqPool#1]
当ch == nil时， 新创建的channel并不在连接池里面，channelId = -1，S.channels[channelId].notifyConfirm接收不到该channel的ack。
应该修改为 cha.notifyConfirm
cha在前面声明

**Comment by Braveheart7854** [comment]
对的，你说的是正确的，会马上作出更正

**Comment by kurolz** [comment]
> 对的，你说的是正确的，会马上作出更正

另外请问你这边有用到生产环境么？运行一段时间后，还是遇到接收不到Confirm的问题，一直没解决，可以留下联系方式请教么？

**Comment by Braveheart7854** [comment]
有用在生产环境的，我暂时没有遇到收不到Confirm的问题，可能跟并发量和机子性能有关系，没达到这个性能瓶颈。如果遇到接收不到Confirm时，会返回一个err，需要判断一下，并记录下来需要重试的消息。

**Comment by Braveheart7854** [comment]
> > 对的，你说的是正确的，会马上作出更正
> 
> 另外请问你这边有用到生产环境么？运行一段时间后，还是遇到接收不到Confirm的问题，一直没解决，可以留下联系方式请教么？

3272534298 我的qq
